// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: XALmqdRmrSVWCYtKbDVCa
// Component: 11brxWskHYs7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TestComponentPvt from "../../TestComponentPvt"; // plasmic-import: B3s19ZmPKdxD/component
import TestComponentExtRo from "../../TestComponentExtRo"; // plasmic-import: 7yyk57E45CRP/component
import TestComponentExtRw from "../../TestComponentExtRw"; // plasmic-import: VEs1_XRysBDn/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: XALmqdRmrSVWCYtKbDVCa/projectcss
import sty from "./PlasmicUsingTestComponents.module.css"; // plasmic-import: 11brxWskHYs7/css

createPlasmicElementProxy;

export type PlasmicUsingTestComponents__VariantMembers = {};
export type PlasmicUsingTestComponents__VariantsArgs = {};
type VariantPropType = keyof PlasmicUsingTestComponents__VariantsArgs;
export const PlasmicUsingTestComponents__VariantProps =
  new Array<VariantPropType>();

export type PlasmicUsingTestComponents__ArgsType = {};
type ArgPropType = keyof PlasmicUsingTestComponents__ArgsType;
export const PlasmicUsingTestComponents__ArgProps = new Array<ArgPropType>();

export type PlasmicUsingTestComponents__OverridesType = {
  root?: Flex__<"div">;
  testComponentPvt?: Flex__<typeof TestComponentPvt>;
  testComponentExtRo?: Flex__<typeof TestComponentExtRo>;
  testComponentExtRw?: Flex__<typeof TestComponentExtRw>;
};

export interface DefaultUsingTestComponentsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUsingTestComponents__RenderFunc(props: {
  variants: PlasmicUsingTestComponents__VariantsArgs;
  args: PlasmicUsingTestComponents__ArgsType;
  overrides: PlasmicUsingTestComponents__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "testComponentExtRo.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "testComponentExtRw.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "test"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <TestComponentPvt
            data-plasmic-name={"testComponentPvt"}
            data-plasmic-override={overrides.testComponentPvt}
            className={classNames("__wab_instance", sty.testComponentPvt)}
          />

          <TestComponentExtRo
            data-plasmic-name={"testComponentExtRo"}
            data-plasmic-override={overrides.testComponentExtRo}
            className={classNames("__wab_instance", sty.testComponentExtRo)}
            onValueChange={generateStateOnChangeProp($state, [
              "testComponentExtRo",
              "value"
            ])}
          />

          <TestComponentExtRw
            data-plasmic-name={"testComponentExtRw"}
            data-plasmic-override={overrides.testComponentExtRw}
            className={classNames("__wab_instance", sty.testComponentExtRw)}
            onValueChange={generateStateOnChangeProp($state, [
              "testComponentExtRw",
              "value"
            ])}
            value={generateStateValueProp($state, [
              "testComponentExtRw",
              "value"
            ])}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "testComponentPvt",
    "testComponentExtRo",
    "testComponentExtRw"
  ],
  testComponentPvt: ["testComponentPvt"],
  testComponentExtRo: ["testComponentExtRo"],
  testComponentExtRw: ["testComponentExtRw"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  testComponentPvt: typeof TestComponentPvt;
  testComponentExtRo: typeof TestComponentExtRo;
  testComponentExtRw: typeof TestComponentExtRw;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUsingTestComponents__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUsingTestComponents__VariantsArgs;
    args?: PlasmicUsingTestComponents__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUsingTestComponents__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicUsingTestComponents__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUsingTestComponents__ArgProps,
          internalVariantPropNames: PlasmicUsingTestComponents__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUsingTestComponents__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUsingTestComponents";
  } else {
    func.displayName = `PlasmicUsingTestComponents.${nodeName}`;
  }
  return func;
}

export const PlasmicUsingTestComponents = Object.assign(
  // Top-level PlasmicUsingTestComponents renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    testComponentPvt: makeNodeComponent("testComponentPvt"),
    testComponentExtRo: makeNodeComponent("testComponentExtRo"),
    testComponentExtRw: makeNodeComponent("testComponentExtRw"),

    // Metadata about props expected for PlasmicUsingTestComponents
    internalVariantProps: PlasmicUsingTestComponents__VariantProps,
    internalArgProps: PlasmicUsingTestComponents__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicUsingTestComponents;
/* prettier-ignore-end */
